/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ApiStorefrontHandlerRouteImport } from './routes/api.storefront-handler'
import { Route as ApiStorefrontAgentRouteImport } from './routes/api.storefront-agent'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiCartRouteImport } from './routes/api.cart'
import { Route as ApiSkillsNameRouteImport } from './routes/api.skills.$name'
import { Route as ApiOrdersOrderIdRouteImport } from './routes/api.orders.$orderId'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontHandlerRoute = ApiStorefrontHandlerRouteImport.update({
  id: '/api/storefront-handler',
  path: '/api/storefront-handler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontAgentRoute = ApiStorefrontAgentRouteImport.update({
  id: '/api/storefront-agent',
  path: '/api/storefront-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCartRoute = ApiCartRouteImport.update({
  id: '/api/cart',
  path: '/api/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsNameRoute = ApiSkillsNameRouteImport.update({
  id: '/api/skills/$name',
  path: '/api/skills/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdRoute = ApiOrdersOrderIdRouteImport.update({
  id: '/api/orders/$orderId',
  path: '/api/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/api/cart': typeof ApiCartRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/storefront-agent': typeof ApiStorefrontAgentRoute
  '/api/storefront-handler': typeof ApiStorefrontHandlerRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/skills/$name': typeof ApiSkillsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/api/cart': typeof ApiCartRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/storefront-agent': typeof ApiStorefrontAgentRoute
  '/api/storefront-handler': typeof ApiStorefrontHandlerRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/skills/$name': typeof ApiSkillsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/api/cart': typeof ApiCartRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/storefront-agent': typeof ApiStorefrontAgentRoute
  '/api/storefront-handler': typeof ApiStorefrontHandlerRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/orders/$orderId': typeof ApiOrdersOrderIdRoute
  '/api/skills/$name': typeof ApiSkillsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/api/cart'
    | '/api/checkout'
    | '/api/storefront-agent'
    | '/api/storefront-handler'
    | '/orders/$orderId'
    | '/api/orders/$orderId'
    | '/api/skills/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/api/cart'
    | '/api/checkout'
    | '/api/storefront-agent'
    | '/api/storefront-handler'
    | '/orders/$orderId'
    | '/api/orders/$orderId'
    | '/api/skills/$name'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/api/cart'
    | '/api/checkout'
    | '/api/storefront-agent'
    | '/api/storefront-handler'
    | '/orders/$orderId'
    | '/api/orders/$orderId'
    | '/api/skills/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiCartRoute: typeof ApiCartRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiStorefrontAgentRoute: typeof ApiStorefrontAgentRoute
  ApiStorefrontHandlerRoute: typeof ApiStorefrontHandlerRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ApiOrdersOrderIdRoute: typeof ApiOrdersOrderIdRoute
  ApiSkillsNameRoute: typeof ApiSkillsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront-handler': {
      id: '/api/storefront-handler'
      path: '/api/storefront-handler'
      fullPath: '/api/storefront-handler'
      preLoaderRoute: typeof ApiStorefrontHandlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront-agent': {
      id: '/api/storefront-agent'
      path: '/api/storefront-agent'
      fullPath: '/api/storefront-agent'
      preLoaderRoute: typeof ApiStorefrontAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cart': {
      id: '/api/cart'
      path: '/api/cart'
      fullPath: '/api/cart'
      preLoaderRoute: typeof ApiCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/$name': {
      id: '/api/skills/$name'
      path: '/api/skills/$name'
      fullPath: '/api/skills/$name'
      preLoaderRoute: typeof ApiSkillsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId': {
      id: '/api/orders/$orderId'
      path: '/api/orders/$orderId'
      fullPath: '/api/orders/$orderId'
      preLoaderRoute: typeof ApiOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ApiCartRoute: ApiCartRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiStorefrontAgentRoute: ApiStorefrontAgentRoute,
  ApiStorefrontHandlerRoute: ApiStorefrontHandlerRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ApiOrdersOrderIdRoute: ApiOrdersOrderIdRoute,
  ApiSkillsNameRoute: ApiSkillsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
