/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStorefrontHandlerRouteImport } from './routes/api.storefront-handler'
import { Route as ApiStorefrontAgentRouteImport } from './routes/api.storefront-agent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontHandlerRoute = ApiStorefrontHandlerRouteImport.update({
  id: '/api/storefront-handler',
  path: '/api/storefront-handler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorefrontAgentRoute = ApiStorefrontAgentRouteImport.update({
  id: '/api/storefront-agent',
  path: '/api/storefront-agent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/storefront-agent': typeof ApiStorefrontAgentRoute
  '/api/storefront-handler': typeof ApiStorefrontHandlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/storefront-agent': typeof ApiStorefrontAgentRoute
  '/api/storefront-handler': typeof ApiStorefrontHandlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/storefront-agent': typeof ApiStorefrontAgentRoute
  '/api/storefront-handler': typeof ApiStorefrontHandlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/storefront-agent' | '/api/storefront-handler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/storefront-agent' | '/api/storefront-handler'
  id: '__root__' | '/' | '/api/storefront-agent' | '/api/storefront-handler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStorefrontAgentRoute: typeof ApiStorefrontAgentRoute
  ApiStorefrontHandlerRoute: typeof ApiStorefrontHandlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront-handler': {
      id: '/api/storefront-handler'
      path: '/api/storefront-handler'
      fullPath: '/api/storefront-handler'
      preLoaderRoute: typeof ApiStorefrontHandlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storefront-agent': {
      id: '/api/storefront-agent'
      path: '/api/storefront-agent'
      fullPath: '/api/storefront-agent'
      preLoaderRoute: typeof ApiStorefrontAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStorefrontAgentRoute: ApiStorefrontAgentRoute,
  ApiStorefrontHandlerRoute: ApiStorefrontHandlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
