name: autofix.ci

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    name: 🤖 Autofix
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint:fix
      - run: pnpm format
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1
